# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastmcp

# Copy server code
COPY server.py /app/server.py

# Patch server to use PORT env var
RUN sed -i '1i import os' /app/server.py && \
    sed -i "s/port=8000,/port=int(os.getenv('PORT', '8000')),/" /app/server.py

# Expose default port
EXPOSE 8000

# Start server
CMD ["python", "server.py"]
