# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastmcp

# Copy server source code
COPY server.py .

# Expose the port, default from PORT env or 8000
EXPOSE 8000

# Run the server
CMD ["python", "server.py"]
