# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock ./
COPY server.py ./

# Patch server to mount at root to avoid redirect issues
RUN sed -i 's,path="/mcp",path="/",' server.py

# Install dependencies
RUN pip install --no-cache-dir .

# Expose port
EXPOSE 8000

# Default command
CMD ["python3", "server.py"]
